"""GeneratedClip — media produced by AI (M7).

`prompt_hash` uniqueness is ladder rung 0 (the generation cache) — the
single biggest cost saving in the system. `model_id` is recorded per
implementation guide section 6.4: the aggregator (fal.ai) lets the model
change at any time, and this column is what stops the cache from serving
a clip generated by a model you've since moved off.

`job_id` + `status` exist because fal generation is submit-and-poll, not
request-response (implementation guide, Phase M7 advice: "persist the
provider job handle immediately on submit, before anything else... a
crash between submit and persist means you have paid for a clip you can
never find"). A row is inserted at submit time with `status="submitted"`
and `local_path=None`; `mark_completed`/`mark_failed` fill in the rest
once the job resolves. Fake/dry-run generation still inserts directly
with `status="completed"` in the same call, since it never actually waits.

`status="rejected"` + `violated_constraint` (M6.5, A12/A13) record a
generation that violated a Director constraint: billed (`cost_cents`) and
never reusable as a cache hit (the cache-hit check elsewhere only ever
trusts `status == "completed"`), with `local_path=None` since the bytes
are deliberately never written anywhere. `violated_constraint` is a real
column, not something recovered by parsing `error`'s free text - a
resumed run that finds its own prior "rejected" row for this exact
attempt needs the constraint back in a form it can rebuild the next
attempt's prompt from (`app/assets/constraint_check.py::
build_revised_prompt`), without re-generating or re-billing an attempt
already known to fail.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.db.base import Base


class GeneratedClipModel(Base):
    __tablename__ = "generated_clip"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("project.id"), nullable=False
    )
    shot_id: Mapped[str] = mapped_column(String, nullable=False)  # matches IR shot id
    provider: Mapped[str] = mapped_column(String, nullable=False)
    model_id: Mapped[str] = mapped_column(String, nullable=False)
    prompt: Mapped[str] = mapped_column(Text, nullable=False)
    prompt_hash: Mapped[str] = mapped_column(String, nullable=False, unique=True)
    duration_s: Mapped[float | None] = mapped_column(Float, nullable=True)
    local_path: Mapped[str | None] = mapped_column(String, nullable=True)
    cost_cents: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    job_id: Mapped[str | None] = mapped_column(String, nullable=True)
    status: Mapped[str] = mapped_column(String, nullable=False, default="completed")
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    violated_constraint: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
