"""scope asset dedup per-project, add shot_binding uniqueness

Revision ID: 6a4ee7c1aae3
Revises: ec1b1fb9f37a
Create Date: 2026-08-14 21:41:10.437827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a4ee7c1aae3'
down_revision: Union[str, None] = 'ec1b1fb9f37a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asset_content_hash_key', 'asset', type_='unique')
    op.create_unique_constraint('uq_asset_project_content_hash', 'asset', ['project_id', 'content_hash'])
    op.create_unique_constraint('uq_shot_binding_project_version_shot', 'shot_binding', ['project_id', 'timeline_version', 'shot_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_shot_binding_project_version_shot', 'shot_binding', type_='unique')
    op.drop_constraint('uq_asset_project_content_hash', 'asset', type_='unique')
    op.create_unique_constraint('asset_content_hash_key', 'asset', ['content_hash'])
    # ### end Alembic commands ###
