"""add job_id, status, error columns to generated_clip for fal submit-poll resumability

Revision ID: ea89dbae109b
Revises: 6a4ee7c1aae3
Create Date: 2026-08-14 23:41:00.384612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea89dbae109b'
down_revision: Union[str, None] = '6a4ee7c1aae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('generated_clip', sa.Column('job_id', sa.String(), nullable=True))
    # server_default backfills existing rows (all of which represent
    # already-completed fake/dry-run generations) before the column is
    # made non-nullable; drop the default afterward so new inserts must
    # supply it explicitly via the model.
    op.add_column(
        'generated_clip',
        sa.Column('status', sa.String(), nullable=False, server_default='completed'),
    )
    op.alter_column('generated_clip', 'status', server_default=None)
    op.add_column('generated_clip', sa.Column('error', sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_clip', 'error')
    op.drop_column('generated_clip', 'status')
    op.drop_column('generated_clip', 'job_id')
    # ### end Alembic commands ###
