"""Regression guard for `SelectSfxStep` (long_form_direction.md A8,
2026-09-01).

Adding `SfxKind.DIEGETIC` to the enum turned `SelectSfxStep.run`'s old
`for kind in SfxKind:` loop into a guaranteed `KeyError` on every single
project: `_DEFAULT_QUERIES` has no `"diegetic"` entry (diegetic has no
fixed query list - its "query" is each shot's own `sfx_cue`, and it is
never searched, only generated by `GenerateDiegeticSfxStep`). Fixed by
iterating `_STRUCTURAL_KINDS` instead. These tests pin that invariant so
a future kind added to `SfxKind` without a matching `_DEFAULT_QUERIES`
entry fails here, in milliseconds, rather than in a live workflow run.
"""

from app.schemas.timeline import SfxKind
from app.workflow.steps.select_sfx import _DEFAULT_QUERIES, _STRUCTURAL_KINDS


def test_structural_kinds_excludes_diegetic():
    assert SfxKind.DIEGETIC not in _STRUCTURAL_KINDS


def test_every_structural_kind_has_a_default_query():
    for kind in _STRUCTURAL_KINDS:
        assert kind.value in _DEFAULT_QUERIES


def test_iterating_structural_kinds_never_keyerrors_even_with_a_bare_plan():
    """The exact loop shape `SelectSfxStep.run` uses, with an empty
    `plan.queries` (the `default_sfx_plan()` case) - proof the fix holds,
    not just that the two sets happen to line up."""
    plan_queries: dict[str, list[str]] = {}
    for kind in _STRUCTURAL_KINDS:
        terms = plan_queries.get(kind.value) or _DEFAULT_QUERIES[kind.value]
        assert terms
